POST http://localhost:4002/products
content-type:application/json

{
  "name":"Pasta plastica",
  "price":29.90
}

###
GET http://localhost:4002/products

###
GET http://localhost:4002/products/6084594c-5e7e-4d52-81c2-362e5761c32e

###
PUT http://localhost:4002/products/6084594c-5e7e-4d52-81c2-362e5761c32e
content-type:application/json

{
  "name":"Borracha",
  "price":3.50
}

###
DELETE http://localhost:4002/products/3f0a7a1d-f338-4efd-9874-bad12eb411ef